name: Build and Publish

on:
  pull_request:
    branches: ["main"]
    types:
      - closed

jobs:
  if_merged_build-and-push-docker-image:
    if: github.event.pull_request.merged == true
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find and Replace api key
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "variable_api_key"
          replace: "${{ secrets.FIREBASE_API_KEY }}"
          include: "firebase.js"
          regex: false

      - name: Find and Replace sender id
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "variable_sender_id"
          replace: "${{ secrets.FIREBASE_SENDER_ID }}"
          include: "firebase.js"
          regex: false
      
      - name: Find and Replace app id
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "variable_app_id"
          replace: "${{ secrets.FIREBASE_APP_ID }}"
          include: "firebase.js"
          regex: false

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/microservices:liftlife-frontend

      - name: Push docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservices:liftlife-frontend

